plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - docs/what-is-conda.md
  - docs/environments.md
  - docs/installing-packages.md
  - docs/cheatsheet.md
remote_theme: aksakalli/jekyll-doc-theme@gh-pages 
toc:
  enabled: true
#   h_min: 1
#   h_max: 2
theme: jekyll-theme-hacker