plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - docs/what-is-conda.md
  - docs/environments.md
  - docs/installing-packages.md
  - docs/cheatsheet.md
remote-theme: sighingnow/jekyll-gitbook
toc:
  enabled: true
  h_min: 0
  h_max: 1