{% set name = "intro2conda" %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version')  %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ./
build:
  skip: true # [win]
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed -vv "

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - intro2conda
    - intro2conda.print

about:
  home: https://lsawade.github.io/introduction-to-conda
  license: GPL-3.0+
  license_family: GPL
  license_file: LICENSE 
  summary: Introduction to conda

extra:
  recipe-maintainers:
    - lsawade