{% set name = "intro2conda" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/lsawade/introduction-to-conda

build:
  number: 0
  script: "cd intro2conda {{ PYTHON }} -m pip install . --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - intro2conda
    - intro2conda.print

about:
  home: https://lsawade.github.io/introduction-to-conda/
  license: GPL-3.0+
  license_family: GPL
  license_file: LICENSE 
  summary: Introduction to conda

extra:
  recipe-maintainers:
    - lsawade